version: '3.9'

services:
  db:
    image: postgres:14
    container_name: goyave_db
    restart: always
    environment:
      POSTGRES_USER: goyave
      POSTGRES_PASSWORD: Postgres_goyave
      POSTGRES_DB: prediction_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Expose PostgreSQL sur le port 5433 de l’hôte

  api:
    build: .
    container_name: prediction_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app            # Code source FastAPI
      - ./training:/training  # Scripts et notebooks ML
      - ./data:/data          # Données (si besoin)

volumes:
  postgres_data:
